### ISSUE TITLE
golang=>nodejs

### ISSUE THREAD

**Issue by x0rium** [roytan883/moleculer-go#2]
Hello! Does is it support events emitted from golang to nodejs? I try emit event and subscribe to it in nodejs project. 
In ,my case it returns
level=error msg="Service Not available: device.connected"
in go: 
`				err = pBroker.Emit("device.connected", map[string]interface{}{
					"ID": "asdasd",
				})
`
in node:
`
const myService = {
    name: "myService",
    events: {
        "device.connected"(device) {
            console.log(device)
        },
        "**"(payload, sender, event) {
            console.log(`Event '${event}' received from ${sender} node:`, payload)
        }
    },
};

`

**Comment by roytan883** [comment]
@molotsnk 
> Yes, It support events. Here is my test result from go->nodejs:

Go:
```
INFO[06-19 18:55:25.975271] broker.Emit user.create start
INFO[06-19 18:55:25.975346] Emit: user.create
INFO[06-19 18:55:25.975415] Emit referNodes = map[rts-demo-dev-88-0:rts-demo-dev-88-0]
INFO[06-19 18:55:25.975554] Emit topic: MOL.EVENT.rts-demo-dev-88-0
INFO[06-19 18:55:25.975601] Emit data: {"ver":"3","sender":"moleculer-go-demo","event":"user.create","data":{"user":"userA","status":"create"},"groups":null,"broadcast":false}
INFO[06-19 18:55:25.975780] broker.Emit user.create end, err: <nil>
```

Nodejs: `"name": "moleculer",  "version": "0.12.8",`
```
=====[rts-demo-dev-88-0]=====>>>>> started
INFO -> demo Event userCreate called: payload =  { user: 'userA', status: 'create' }

```

You can turn on `LogLevel: moleculer.DebugLevel,` at `examples/moleculer-go-demo.go` to see what happening. Just make sure you have disable `// service.Events["user.create"] = onEventUserCreate` in go example, because `broker.Emit` and `broker.Broadcast` are different.

**Comment by x0rium** [comment]
Thanks!
